@startuml
class Employee{
}
class EmployeeFacade{
}
class EmployeeGateway{
}
class EmployeePolicy{
}
class EmployeeReports{
}

EmployeeFacade -- EmployeeGateway
EmployeeFacade -- EmployeePolicy
EmployeeFacade -- EmployeeReports

Employee - EmployeeFacade

@enduml