@startuml
interface FeatheredCreature{
+ molt()
}
interface FlyingCreature{
+ fly()
}
interface SwimmingCreature{
+ swim()
}

class Penguin
class Eagle

FeatheredCreature <-- Eagle
FeatheredCreature <-- Penguin

FlyingCreature <-- Eagle
SwimmingCreature <-- Penguin

@enduml